### PR TITLE
OrmLiteCursorAdapter return a Typed entity instead a cursor

### PR DESCRIPTION
**Pull request by guitcastro**
It´s nice to take more advantage of Generic

### CODE REVIEW

**Comment by j256** [comment]
Sorry, I just don't get this merge request.  It removes a ton of code.  Am I understanding it right?

**Comment by guitcastro** [comment]
@j256  Sorry I am not familiar with github PR.

The only commit related to this PR is this one https://github.com/guitcastro/ormlite-android/commit/3fb3c483525788f71e9639491ebe2647f623d453

The commit that remove a ton of code is related to this issue:

https://github.com/guitcastro/ormlite-android/commit/de028277563ae51d87c563929b17a518484bed75


And the other commit does not make sense for you (only for my fork).

I don´t know why those commits were added to this PR. = /

**Comment by j256** [comment]
I've hand merged the one commit but I can't make the permanent without breaking existing code, right?  So I used you `getTypedItem(...)` name instead.  Hope this is adequate.

**Comment by j256** [comment]
See: https://github.com/j256/ormlite-android/commit/fa55a367f3acb7418d7ad62db39f874d1eff3ead

**Comment by VincentFTS** [comment]
What code would this break ?
It should keep its name (getItem) as it greatly overides the extended class (CursorAdapter) method !

**Comment by j256** [comment]
But it's returning a completely different object.  Anyone using that method would have code that wouldn't compile, right?

**Comment by VincentFTS** [comment]
My humblest apologies, you're right, I misread the CursorAdapter method return type.

**Pull request closed without merging**
